apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubernetes/

images:
- name: LOGOUT_IMAGE
  newName: artursreg.azurecr.io/logout407:latest

- name: PINGPONG_IMAGE
  newName: artursreg.azurecr.io/pinpong407:latest
