apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubernetes/db-config.yaml
- kubernetes/db-secret.yaml
- kubernetes/ingress.yaml
- kubernetes/logout-depl.yaml
- kubernetes/logout-svc.yaml
- kubernetes/ping-depl.yaml
- kubernetes/ping-svc.yaml
- kubernetes/postgres-pvc.yaml
- kubernetes/postgres-svc.yaml
- kubernetes/postgres.yaml


images:
- name: LOGOUT_IMAGE
  newName: artursreg.azurecr.io/logout407
  newTag: latest
- name: PINGPONG_IMAGE
  newName: artursreg.azurecr.io/pingpong407
  newTag: latest
- name: NGINX_IMAGE
  newName: nginx
  newTag: stable-perl
